<?php
/**
 * @file
 * Provides OAuth2 server functionality.
 */

/**
 * Implements hook_init().
 *
 * Nags the user about the missing library on OAuth2 admin pages.
 */
function oauth2_client_init() {
  $item = menu_get_item();
  if ($item['access'] && strpos($item['path'], 'admin/structure/oauth2-clients') === 0) {
    $path = oauth2_client_get_library_path();
    // Check for the existence of one file from the library.
    if (!$path || !file_exists($path . '/Client.php')) {
      $message = t('The PHP-OAuth2 client library is required for the oauth2_client module to function.
        Download the library from <a href="https://github.com/adoy/PHP-OAuth2" target="_blank">GitHub</a> and place it in <em>!path</em>.', array('!path' => $path));
      drupal_set_message($message, 'error');
    }
  }
}

/**
 * Implements hook_libraries_info().
 */
function oauth2_client_libraries_info() {
  $libraries = array();
  $libraries['PHP-OAuth2'] = array(
    'name' => 'OAuth2 Client',
    'vendor url' => 'https://github.com/adoy/PHP-OAuth2',
  );
  return $libraries;
}

/**
 * Returns the filesystem path to the PHP-OAuth2 library.
 */
function oauth2_client_get_library_path() {
  $path = 'sites/all/libraries/PHP-OAuth2';
  // If installed, use the Libraries API to locate the library.
  if (module_exists('libraries')) {
    module_load_include('module', 'libraries');
    $path = libraries_get_path('PHP-OAuth2');
  }

  return $path;
}

/**
 * Gets all defined oauth2_clients.
 */
function oauth2_client_get_all() {
  $data = array();
  foreach (module_implements('oauth2_clients') as $module) {
    $result = call_user_func($module . '_oauth2_clients');
    if (isset($result) && is_array($result)) {
      foreach ($result as $name => $item) {
        $item += array('module' => $module);
        $data[$name] = $item;
      }
    }
  }
  drupal_alter('oauth2_clients', $data);
  return $data;
}

/**
 * Implements hook_oauth2_clients().
 * Defines test clients.
 */
function oauth2_client_oauth2_clients() {
  // for testing user-password flow
  $oauth2_clients['test1'] = array(
    'token_endpoint' => 'https://dev.l10n.org.xx/oauth2/token',
    'authentication_flow' => 'user-password',
    'client_id' => 'test2',
    'client_secret' => 'test2',
    'username' => 'user1',
    'password' => 'user1',
  );

  // for testing client-credentials flow
  $oauth2_clients['test2'] = array(
    'token_endpoint' => 'https://dev.l10n.org.xx/oauth2/token',
    'authentication_flow' => 'client-credentials',
    'client_id' => 'test2',
    'client_secret' => 'test2',
  );

  // for testing server-side flow
  $oauth2_clients['test3'] = array(
    'token_endpoint' => 'https://dev.l10n.org.xx/oauth2/token',
    'authentication_flow' => 'server-side',
    'client_id' => 'test1',
    'client_secret' => 'test1',
    'authorization_endpoint' => 'https://dev.l10n.org.xx/oauth2/authorize',
    'redirect_uri' => 'https://dev.l10n.org.xx/oauth2/authorized',
  );

  return $oauth2_clients;
}

/**
 * Load an oauth2 client.
 *
 * @return OAuth2Client
 *   Returns an OAuth2Client or NULL if not found.
 */
function oauth2_client_load($name) {
  $oauth2_clients = oauth2_client_get_all();

  if (!isset($oauth2_clients[$name])) {
    return NULL;
  }
  $client = $oauth2_clients[$name];

  switch ($client['authentication_flow']) {
    case 'client-credentials':
      $oauth2_client = new OAuth2Client(
        'client-credentials',
        $client['client_id'],
        $client['client_secret'],
        $client['token_endpoint']
      );
      break;

    case 'user-password':
      $oauth2_client = new OAuth2Client(
        'user-password',
        $client['client_id'],
        $client['client_secret'],
        $client['token_endpoint'],
        array(
          'username' => $client['username'],
          'password' => $client['password'],
        )
      );
      break;

    case 'server-side':
      $oauth2_client = new OAuth2Client(
        'server-side',
        $client['client_id'],
        $client['client_secret'],
        $client['token_endpoint'],
        array(
          'authorization_endpoint' => $client['authorization_endpoint'],
          'redirect_uri' => $client['redirect_uri'],
        )
      );
      break;

    default:
      $oauth2_client = NULL;
      break;
  }

  //print '<xmp>';  print_r($oauth2_client);  print '</xmp>';  exit(0);  //debug
  return $oauth2_client;
}

/**
 * Implements hook_menu().
 */
function oauth2_client_menu() {
  $items = array();
  $items['oauth2/authorized'] = array(
    'page callback' => 'oauth2_client_authorized',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['oauth2/test'] = array(
    'page callback' => 'oauth2_client_test',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * An authorized request in server-side flow
 * will be redirected here (having variables
 * 'code' and 'state').
 */
function oauth2_client_authorized() {
  if (isset($_SESSION['oauth2_client_destination'])) {
    $destination = $_SESSION['oauth2_client_destination'];
    drupal_goto($destination, array('query' => $_REQUEST));
  }
}

/**
 * Trying test clients.
 */
function oauth2_client_test($nr) {
  $client_name = 'test' . $nr;
  $oauth2_client = oauth2_client_load($client_name);
  if (!$oauth2_client) {
    drupal_set_message("Client '$client_name' could not be found!", 'error');
    print "Client '$client_name' could not be found!";
    return;
  }

  // get an access token
  try {
    $access_token = $oauth2_client->getAccessToken();
  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
  }

  // get a resource and output it
  $base_url = "https://dev.l10n.org.xx";
  $url = "$base_url/btr/translations/next?lng=sq&access_token=$access_token";
  $response = drupal_http_request($url);
  $response->data = json_decode($response->data);
  print '<xmp>';  print_r($response);  print '</xmp>';  //debug
}
