<?php
/**
 * @file
 * Testing OAuth2 client functionality.
 */

/**
 * Implements hook_oauth2_clients().
 */
function oauth2_client_test_oauth2_clients() {
  $oauth2_clients = array();

  // For testing client-credentials flow.
  $oauth2_clients['client-credentials'] = array(
    'token_endpoint' => url('oauth2/token', array('absolute' => TRUE)),
    'auth_flow' => 'client-credentials',
    'client_id' => 'client1',
    'client_secret' => 'secret1',
  );

  // For testing user-password flow.
  $oauth2_clients['user-password'] = array(
    'token_endpoint' => url('oauth2/token', array('absolute' => TRUE)),
    'auth_flow' => 'user-password',
    'client_id' => 'client1',
    'client_secret' => 'secret1',
    'username' => 'user1',
    'password' => 'pass1',
  );

  // For testing server-side flow.
  $oauth2_clients['server-side'] = array(
    'token_endpoint' => url('oauth2/token', array('absolute' => TRUE)),
    'auth_flow' => 'server-side',
    'client_id' => 'client1',
    'client_secret' => 'secret1',
    'authorization_endpoint' => url('oauth2/authorize', array('absolute' => TRUE)),
    'redirect_uri' => url('oauth2/authorized',  array('absolute' => TRUE)),
    'scope' => 'scope1 scope2',
  );

  return $oauth2_clients;
}

/**
 * Implements hook_menu().
 */
function oauth2_client_test_menu() {
  $items = array();
  $items['oauth2/test'] = array(
    'page callback' => 'oauth2_client_test_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Trying test clients.
 *
 * Call them by opening in browser:
 *   - $base_url/oauth2/test/client-credentials
 *   - $base_url/oauth2/test/user-password
 *   - $base_url/oauth2/test/server-side
 */
function oauth2_client_test_callback($client_name) {
  try {
    // Get an access token and output it.
    $oauth2_client = oauth2_client_load($client_name);
    $access_token = $oauth2_client->getAccessToken();
    print "access_token: $access_token";
  }
  catch (Exception $e) {
    print 'Error: '. $e->getMessage();
  }
}
